example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls'))  
]

wishlist/urls.py
from django.urls import path
from django.conf.urls import include
from wishlist.views import post_ajax_wishlist, show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import show_wishlist_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),  
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit', post_ajax_wishlist, name="post_ajax_wishlist")
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

    

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from urllib import request
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
import json

@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Fauzan Firzandy Khifzan',
    'last_login': request.COOKIES['last_login']
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Fauzan Firzandy Khifzan',
    'last_login': request.COOKIES['last_login']
    }
    return render(request, "wishlist_ajax.html", context)

def post_ajax_wishlist(request):
    if request.method == 'POST':
        nama_barang = request.POST['nama_barang']
        harga_barang = request.POST['harga_barang']
        deskripsi = request.POST['deskripsi']

        ins = BarangWishlist(nama_barang=nama_barang, harga_barang=harga_barang, deskripsi=deskripsi)
        ins.save()

        data = {
            "message" : 'Submitted!'
        }
        json_obj = json.dumps(data, indent = 4)

        return JsonResponse(json.loads(json_obj))
    return render(request, "add_wishlist.html")

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

wishlist/templates/add_wishlist.html
{% extends 'base.html' %} 
<title>Add New Wishlist</title>

{% block content %}
<center>
    <h1>Create Wishlist</h1>
<center>

<div class="addwishlist d-flex justify-content-center align-items-center">

    <form method="POST" action="" class="d-flex flex-column">
      {% csrf_token %}
      <div class="form d-flex flex-column justify-content-between gap-2">
        <label for="nama_barang">Nama Barang</label>
        <input
          type="text"
          name="nama_barang"
          id="nama_barang"
          placeholder="Nama Barang"
        />
      </div>
      <div class="form d-flex flex-column justify-content-between gap-2">
        <label for="harga_barang">Harga Barang</label>
        <input
          name="harga_barang"
          id="harga_barang"
          placeholder="Harga Barang"
        />
      </div>
      <div class="form d-flex flex-column justify-content-between gap-2">
        <label for="deskripsi">Deskripsi</label>
        <input
          name="deskripsi"
          id="deskripsi"
          placeholder="Deskripsi"
        />
      </div>
      <button class="btn btn-success">Submit</button>
    </form>
    <center>
        <center id="message"></center>
    <center>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    $('form').submit(function (event) {
      const formData = {
        csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
        nama_barang: $('#nama_barang').val(),
        harga_barang: parseInt($('#harga_barang').val()),
        deskripsi: $('#deskripsi').val(),
      };

      $.ajax({
        type: 'POST',
        url: '/wishlist/ajax/submit',
        data: formData,
        dataType: 'json',
        encode: true,
      }).done(function (data) {
        $('#message').text(data.message);
      });

      event.preventDefault();
    });
  });
</script>
{% endblock content %}

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

<style>

.gradient-custom {
    background: #6a11cb;
    background: -webkit-linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1));
    background: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1))
}
</style>

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}

<style>
table {
    width: fit-content;
    text-align: center;
}
table td {
    border: 1px solid #ccc;
}
</style>

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="mx-auto navbar-brand disabled" href="#">Hello, {{nama}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'wishlist:logout' %}">Logout</a>
        </li>
      </ul>
    </div>
</nav>

<div>
<table class="table table-hover w-50 mx-auto table-bordered">
    <thead class="thead-dark">
        <tr class="table-dark">
            <th scope="col" >Nama Barang</th>
            <th scope="col" >Harga Barang</th>
            <th scope="col" >Deskripsi</th>
        </tr>
    </thead>    
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
{% for barang in list_barang %}
    <tr>
        <th>{{barang.nama_barang}}</th>
        <th>{{barang.harga_barang}}</th>
        <th>{{barang.deskripsi}}</th>
    </tr>
{% endfor %}
</table>
</div>

<h5 class="w-50 mx-auto">Sesi terakhir login: {{ last_login }}</h5>

{% endblock content %}  

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}

<style>
table {
    width: fit-content;
    text-align: center;
}
table td {
    border: 1px solid #ccc;
}
</style>

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="mx-auto navbar-brand disabled" href="#">Hello, {{nama}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'wishlist:logout' %}">Logout</a>
        </li>
      </ul>
    </div>
</nav>

<div>
<table class="table table-hover w-50 mx-auto table-bordered">
    <thead class="thead-dark">
        <tr class="table-dark">
            <th scope="col" >Nama Barang</th>
            <th scope="col" >Harga Barang</th>
            <th scope="col" >Deskripsi</th>
        </tr>
    </thead>    
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
{% for barang in list_barang %}
    <tr>
        <th>{{barang.nama_barang}}</th>
        <th>{{barang.harga_barang}}</th>
        <th>{{barang.deskripsi}}</th>
    </tr>
{% endfor %}
</table>
</div>

<h5 class="w-50 mx-auto">Sesi terakhir login: {{ last_login }}</h5>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
    $(document).ready(function(){
      $.get("/wishlist/json", function(data) {
        data.map((each) =>
            $('#table').append(`<tr>
        <td>${each.fields.nama_barang}</td>
        <td>${each.fields.harga_barang}</td>
        <td>${each.fields.deskripsi}</td>
        </tr>`)
        );
        });
    });
</script>

{% endblock content %}  